#!/usr/bin/env python3
"""
Check whether distinct parameter combinations share the same optimal actions.

This script is designed for goal-conditioned IRP cloth HDF5 files generated by:
    convert_irp_cloth_goals_to_robomimic.py
"""

import argparse
from collections import defaultdict
from itertools import combinations
from pathlib import Path
from typing import Dict, List, Tuple

import h5py
import numpy as np


Record = Dict[str, object]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Report optimal-action collisions across parameter combinations in IRP cloth goal HDF5."
    )
    parser.add_argument("--input", type=str, required=True, help="Path to HDF5 dataset")
    parser.add_argument("--atol", type=float, default=1e-6, help="Absolute tolerance for comparing actions")
    parser.add_argument("--rtol", type=float, default=1e-6, help="Relative tolerance for comparing actions")
    parser.add_argument("--show-limit", type=int, default=20, help="Max collision entries to print per section")
    return parser.parse_args()


def load_records(hdf5_path: Path) -> List[Record]:
    records: List[Record] = []
    with h5py.File(hdf5_path, "r") as f:
        if "data" not in f:
            raise KeyError("Expected group 'data' not found in HDF5.")
        demos = sorted(f["data"].keys(), key=lambda x: int(x.split("_")[-1]))
        for demo_key in demos:
            demo = f["data"][demo_key]
            goal_id = int(demo.attrs["goal_id"])
            size_id = int(np.asarray(demo["obs/param_size_id"])[0])
            density_id = int(np.asarray(demo["obs/param_density_id"])[0])
            action = np.asarray(demo["actions"])[0].astype(np.float64)
            records.append(
                {
                    "demo_key": demo_key,
                    "goal_id": goal_id,
                    "size_id": size_id,
                    "density_id": density_id,
                    "action": action,
                }
            )
    return records


def same_action(a: np.ndarray, b: np.ndarray, atol: float, rtol: float) -> bool:
    return bool(np.allclose(a, b, atol=atol, rtol=rtol))


def format_combo(size_id: int, density_id: int) -> str:
    return f"(size_id={size_id}, density_id={density_id})"


def report_per_goal_collisions(records: List[Record], atol: float, rtol: float, show_limit: int) -> Tuple[int, int]:
    by_goal: Dict[int, List[Record]] = defaultdict(list)
    for rec in records:
        by_goal[int(rec["goal_id"])].append(rec)

    total_goal_ids = len(by_goal)
    goals_with_collision = 0

    print("=== Per-goal shared optimal actions ===")
    for goal_id in sorted(by_goal.keys()):
        recs = by_goal[goal_id]
        collisions = []
        for i, j in combinations(range(len(recs)), 2):
            ri = recs[i]
            rj = recs[j]
            combo_i = (int(ri["size_id"]), int(ri["density_id"]))
            combo_j = (int(rj["size_id"]), int(rj["density_id"]))
            if combo_i == combo_j:
                continue
            if same_action(np.asarray(ri["action"]), np.asarray(rj["action"]), atol=atol, rtol=rtol):
                collisions.append((ri, rj))

        if collisions:
            goals_with_collision += 1
            print(f"goal_id={goal_id}: {len(collisions)} collision pair(s)")
            for pair_idx, (ri, rj) in enumerate(collisions[:show_limit]):
                action = np.asarray(ri["action"], dtype=np.float64)
                print(
                    "  "
                    f"{pair_idx + 1}. {format_combo(int(ri['size_id']), int(ri['density_id']))} demo={ri['demo_key']} "
                    f"<-> {format_combo(int(rj['size_id']), int(rj['density_id']))} demo={rj['demo_key']} "
                    f"action={np.array2string(action, precision=8, separator=', ')}"
                )
            if len(collisions) > show_limit:
                print(f"  ... {len(collisions) - show_limit} more")
        else:
            print(f"goal_id={goal_id}: no collisions")

    print(
        f"Per-goal summary: {goals_with_collision}/{total_goal_ids} goal(s) have at least one "
        "shared-action parameter pair."
    )
    print("")
    return total_goal_ids, goals_with_collision


def report_all_goal_signature_collisions(
    records: List[Record], atol: float, rtol: float, show_limit: int
) -> Tuple[int, List[Tuple[Tuple[int, int], Tuple[int, int]]]]:
    all_goal_ids = sorted({int(rec["goal_id"]) for rec in records})
    combo_to_goal_action: Dict[Tuple[int, int], Dict[int, np.ndarray]] = defaultdict(dict)

    for rec in records:
        combo = (int(rec["size_id"]), int(rec["density_id"]))
        goal_id = int(rec["goal_id"])
        combo_to_goal_action[combo][goal_id] = np.asarray(rec["action"], dtype=np.float64)

    combos = sorted(combo_to_goal_action.keys())
    missing = [combo for combo in combos if set(combo_to_goal_action[combo].keys()) != set(all_goal_ids)]
    if missing:
        print(
            "Warning: some parameter combos do not contain all goals; skipping them for all-goals collision check:"
        )
        for combo in missing[:show_limit]:
            present = sorted(combo_to_goal_action[combo].keys())
            print(f"  {format_combo(combo[0], combo[1])} has goals {present}")
        if len(missing) > show_limit:
            print(f"  ... {len(missing) - show_limit} more")

    valid_combos = [combo for combo in combos if combo not in set(missing)]

    pair_collisions: List[Tuple[Tuple[int, int], Tuple[int, int]]] = []
    for combo_a, combo_b in combinations(valid_combos, 2):
        all_match = True
        for goal_id in all_goal_ids:
            action_a = combo_to_goal_action[combo_a][goal_id]
            action_b = combo_to_goal_action[combo_b][goal_id]
            if not same_action(action_a, action_b, atol=atol, rtol=rtol):
                all_match = False
                break
        if all_match:
            pair_collisions.append((combo_a, combo_b))

    print("=== Shared action signature across ALL goals ===")
    if pair_collisions:
        print(f"Found {len(pair_collisions)} collision pair(s) with identical actions for every goal.")
        for idx, (combo_a, combo_b) in enumerate(pair_collisions[:show_limit]):
            print(
                f"  {idx + 1}. {format_combo(combo_a[0], combo_a[1])} <-> "
                f"{format_combo(combo_b[0], combo_b[1])}"
            )
        if len(pair_collisions) > show_limit:
            print(f"  ... {len(pair_collisions) - show_limit} more")
    else:
        print("No parameter-combo pair shares identical optimal actions across all goals.")
    print("")

    return len(valid_combos), pair_collisions


def main() -> None:
    args = parse_args()
    hdf5_path = Path(args.input).expanduser().resolve()
    if not hdf5_path.exists():
        raise FileNotFoundError(f"HDF5 file not found: {hdf5_path}")

    records = load_records(hdf5_path)
    if len(records) == 0:
        raise RuntimeError("No demos found.")

    print(f"Input: {hdf5_path}")
    print(f"Loaded demos: {len(records)}")
    print(f"Tolerance: atol={args.atol}, rtol={args.rtol}")
    print("")

    total_goals, goals_with_collision = report_per_goal_collisions(
        records=records,
        atol=args.atol,
        rtol=args.rtol,
        show_limit=args.show_limit,
    )
    valid_combo_count, all_goal_pair_collisions = report_all_goal_signature_collisions(
        records=records,
        atol=args.atol,
        rtol=args.rtol,
        show_limit=args.show_limit,
    )

    print("=== Final summary ===")
    print(f"Goals analyzed: {total_goals}")
    print(f"Goals with per-goal collisions: {goals_with_collision}")
    print(f"Parameter combos with complete goal coverage: {valid_combo_count}")
    print(f"Pairs colliding across all goals: {len(all_goal_pair_collisions)}")


if __name__ == "__main__":
    main()
