#!/usr/bin/env python3
"""
Extract one (param_size_id, param_density_id) slice from an IRP rope goal HDF5.

Input is expected to follow the structure generated by:
    convert_irp_rope_goals_to_robomimic.py
"""

import argparse
from pathlib import Path
from typing import Dict

import h5py
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Extract demos for one rope parameter pair from IRP rope goal HDF5."
    )
    parser.add_argument("--input", type=str, required=True, help="Input HDF5 file path")
    parser.add_argument("--output", type=str, required=True, help="Output HDF5 file path")
    parser.add_argument("--size-idx", type=int, required=True, help="Target obs/param_size_id")
    parser.add_argument("--density-idx", type=int, required=True, help="Target obs/param_density_id")
    parser.add_argument(
        "--num-goals",
        type=int,
        default=4,
        help="Expected number of goals / demos for this pair (default: 4)",
    )
    parser.add_argument("--overwrite", action="store_true", help="Overwrite output if it exists")
    return parser.parse_args()


def sorted_demo_keys(data_group: h5py.Group):
    return sorted(list(data_group.keys()), key=lambda x: int(x.split("_")[-1]))


def main() -> None:
    args = parse_args()

    input_path = Path(args.input).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path}")
    if output_path.exists() and not args.overwrite:
        raise FileExistsError(f"Output exists: {output_path}. Use --overwrite to replace.")
    if args.num_goals <= 0:
        raise ValueError(f"--num-goals must be positive, got {args.num_goals}")

    with h5py.File(input_path, "r") as fin:
        if "data" not in fin:
            raise KeyError("Input file missing top-level group 'data'.")

        data_in = fin["data"]
        goal_to_demo: Dict[int, str] = {}
        for demo_key in sorted_demo_keys(data_in):
            demo = data_in[demo_key]
            size_id = int(np.asarray(demo["obs/param_size_id"])[0])
            density_id = int(np.asarray(demo["obs/param_density_id"])[0])
            if size_id != args.size_idx or density_id != args.density_idx:
                continue

            goal_id = int(demo.attrs["goal_id"])
            if goal_id in goal_to_demo:
                raise RuntimeError(
                    f"Found duplicate demos for goal_id={goal_id} at pair "
                    f"({args.size_idx}, {args.density_idx}): {goal_to_demo[goal_id]} and {demo_key}."
                )
            goal_to_demo[goal_id] = demo_key

        if not goal_to_demo:
            raise RuntimeError(
                f"No demos found for pair (size_idx={args.size_idx}, density_idx={args.density_idx})."
            )
        if len(goal_to_demo) != args.num_goals:
            found_goals = sorted(goal_to_demo.keys())
            raise RuntimeError(
                f"Expected {args.num_goals} goals for pair (size_idx={args.size_idx}, "
                f"density_idx={args.density_idx}), but found {len(goal_to_demo)} goals: {found_goals}"
            )

        ordered_goal_ids = sorted(goal_to_demo.keys())

        if output_path.exists() and args.overwrite:
            output_path.unlink()

        with h5py.File(output_path, "w") as fout:
            data_out = fout.create_group("data")

            for k, v in fin.attrs.items():
                fout.attrs[k] = v
            fout.attrs["source_hdf5"] = str(input_path)
            fout.attrs["num_demos"] = int(len(ordered_goal_ids))
            fout.attrs["filtered_size_id"] = int(args.size_idx)
            fout.attrs["filtered_density_id"] = int(args.density_idx)

            for out_idx, goal_id in enumerate(ordered_goal_ids):
                src_demo_key = goal_to_demo[goal_id]
                src_demo = data_in[src_demo_key]
                data_out.copy(src_demo, f"demo_{out_idx}")

    print(
        "Done. Wrote "
        f"{len(goal_to_demo)} demos for pair (size_idx={args.size_idx}, density_idx={args.density_idx}) "
        f"to: {output_path}"
    )


if __name__ == "__main__":
    main()
